plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.vpntest'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.vpntest"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.1.9"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        // Java only, no Kotlin, as requested.
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.activity:activity:1.8.2'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.8.3'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.8.3'
    implementation 'androidx.activity:activity:1.9.0'
}
